# docker-compose-jenkins.yml
services:
  jenkins:
    build:
      context: . # Diretório atual contém o Dockerfile.jenkins
      dockerfile: Dockerfile.jenkins # Especifica o nome do Dockerfile
    # image: jenkins/jenkins:lts-jdk17 # Remova ou comente a linha da imagem
    container_name: jenkins-server
    privileged: true
    user: root # Ainda pode precisar rodar como root para acesso ao socket
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    driver: bridge
