services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/kind:/usr/local/bin/kind
      - /usr/local/bin/kubectl:/usr/local/bin/kubectl
    networks:
      - devops-net
      - kind

volumes:
  jenkins_home:

networks:
  devops-net:
    external: true
  kind:
    external: true
