server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'job'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'instance'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - regex: __meta_docker_container_label_(.+)
        replacement: $1
        target_label: docker_label_$1
      - replacement: /var/log/docker/${1}.log
        source_labels:
        - __meta_docker_container_label_com_docker_compose_service
        - __meta_docker_container_name
        target_label: __path__
