version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch_log
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200" 
      - "9301:9300"
    networks:
      - elk_net
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0 
    container_name: kibana_log
    ports:
      - "5601:5601" 
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_log:9200 
    depends_on:
      - elasticsearch
    networks:
      - elk_net
    restart: unless-stopped

volumes:
  es_data:
    driver: local

networks:
  elk_net:
    driver: bridge
